List<String> images = [
  "assets/images/items/image1.png",
  "assets/images/items/image2.png",
  "assets/images/items/image3.png",
  "assets/images/items/image4.png",
  "assets/images/items/image5.jpg",
  "assets/images/items/image6.png",
  "assets/images/items/image7.png",
  "assets/images/items/image8.png",
  "assets/images/items/image9.png",
  "assets/images/items/image10.jpg",
  "assets/images/items/image11.jpg",
  "assets/images/items/image12.png",
  "assets/images/items/image13.jpg",
  "assets/images/items/image14.jpeg",
  "assets/images/items/image15.jpeg",
  "assets/images/items/image16.jpg",
];

List<String> names = [
  "Kezitil",
  "Kezitil Susp.",
  "Em-B-Plex",
  "Folic Acid",
  "Evergreen",
  "Evergreen Formular",
  "Evergreen Formular",
  "Evergreen Formular",
  "Evergreen Formular",
  "Proception",
  "Ferula Plus",
  "Ferula Plus",
  "Piccan",
  "Hing",
  "Hing",
  "Zecef",
];

List<String> types = [
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
  "Cefuroxime Axetil",
];

List<String> quantity = [
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
  "Oral Suspension - 125mg",
  "Tablet - 20mg",
];

List<String> prices = [
  "400",
  "600",
  "400",
  "1000",
  "500",
  "300",
  "450",
  "350",
  "250",
  "500",
  "350",
  "450",
  "550",
  "350",
  "250",
  "650",
];